reader:
  bind: localhost:8080
  log_datetime: true
  log_debug: true
  max_zoom: 17
  min_zoom: 1
  root_dir: /tmp/metatiles-cacher
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
  writer_addr: http://localhost:8081/add
  x_token: 123

writer:
  bind: localhost:8081
  log_datetime: true
  log_debug: true
  max_zoom: 17
  min_zoom: 1
  root_dir: /tmp/metatiles-cacher
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"
  x_token: 123

sources:
  - name: example
    url: http://example/style/{zxy}

  - name: test
    url: http://test/{zxy}?api_key=123
