cacher:
  bind: localhost:8080
  use_writer: true # write to cache?
  use_source: true # get tiles from remote sources?
  max_age: 86400   # Cache-Control: max-age header
  x_token: 123     # X-Token header for access to /status

zoom:
  min: 1
  max: 17

log:
  datetime: true
  debug: true

filecache:
  root_dir: /tmp/metatiles-cacher

httpclient:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"

sources:
  example: http://example/style/{tile}
  test: http://test/{tile}?api_key=123
