cache:
  bind: localhost:8080
  use_writer: true # write to cache?
  use_source: true # get tiles from remote sources?
  max_age: 86400   # Cache-Control: max-age header
  x_token: 123     # X-Token header for access to /status

log:
  datetime: true
  debug: true

filecache:
  root_dir: /tmp/metatiles-cacher

httpclient:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"

sources:
  # write files to {root_dir}/testsrc1 directory
  - name: testsrc1
    url: http://tilesrv1/style/{tile}

  # write files to {root_dir}/test directory
  - name: testsrc2
    url: http://testsrv2/style/{tile}?api_key=123
    cache_dir: test

  # write files to {root_dir}/test directory but download from another server
  - name: testsrc3
    url: http://testsrv3/style/{tile}
    cache_dir: test
    # define zoom levels for this style
    zoom:
      min: 1
      max: 19
    # redefine zoom levels if point inside this region
    # yaml generates from geofabrik.de kml file
    region:
      file: regions/iran.yaml
      zoom:
        min: 1
        max: 10
