http:
  bind: localhost:8080
  x_token: 123 # X-Token header for access to admin entrypoints
  headers:
    "Cache-Control": "max-age=86400"
    "Access-Control-Allow-Origin": "*"

log:
  datetime: true
  debug: true

cache:
  dir: /tmp/metatiles-cacher
  last_update_expire: 3600

httpclient:
  timeout: 30
  headers:
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0"

fetch:
  enabled: true
  workers: 4
  buffer: 16

sources:
  # write cache to {cache.dir}/testsrc1 directory
  testsrc1:
    url: http://tilesrv1/style/{z}/{x}/{y}.png

  # write cache to {root_dir}/test directory but download from another server
  testsrc2:
    url: http://testsrv2/style/{z}/{x}/{y}.png?key=123
    # define max zoom level for this style
    max_zoom: 14
    last_update: /tmp/metatiles-cacher/planet-import-complete
    # enlarge max zoom level if point inside this region
    # kml downloaded from geofabrik.de
    region:
      file: regions/iran.kml
      max_zoom: 17
