reader:
  bind: localhost:8080
  log_datetime: true
  log_debug: true
  max_zoom: 17
  min_zoom: 1
  root_dir: /tmp/metatiles-cacher
  writer_addr: http://localhost:8081/add/
  x_token: 123

writer:
  bind: localhost:8081
  log_datetime: true
  log_debug: true
  max_zoom: 17
  min_zoom: 1
  root_dir: /tmp/metatiles-cacher
  x_token: 123

sources:
  - name: example
    url: http://example/style/{zxy}

  - name: test
    url: http://test/{zxy}?api_key=123
